[package]
name = "rewp"
version = "0.1.0"
authors = ["Daan van Berkel <daan.v.berkel.1980@gmail.com>"]

[dependencies]
log = "0.3.8"
simplelog = "0.4.3"
dotenv = "0.9.0" 
ws = "*"

[dependencies.iron]
version = "0.5.1"

[dependencies.staticfile]
version = "*"

[dependencies.router]
version = "0.5.1"

[dependencies.mount]
git = "https://github.com/iron/mount.git"
tag = "0.3.0"

[dependencies.logger]
git = "https://github.com/iron/logger.git"

